spring:
  application:
    name: personal-planner
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:planner}
    username: ${DB_USERNAME:planner}
    password: ${DB_PASSWORD:planner}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  file:
    path: ${LOG_PATH:logs}
